version: 0.1
phases:
  install:
    commands:
        - aws s3 cp ./ s3://cicd-pipeline-achyuta-cloud/FileUpload/ --recursive --include "*"
        - aws s3 cp ./ s3://test-bucket-gar-052008640443/ --recursive --include "*"

